import Foundation

/// What the grid is currently reading.
///
/// Was an enum of two cases until vortex arrived; now a struct, because the
/// format is a third thing a source is made of and a directory cannot be asked
/// for it after the fact — a folder has no extension, and the answer is in the
/// files under it. `.file(url)` and `.dataset(url)` still spell what they
/// always did, so pattern matching is the only thing that moved: `kind` and
/// `datasetRoot` are what the handful of places that did it use now.
public struct DataSource: Sendable, Hashable {
    /// Whether this is one file or a folder read as one table.
    public enum Kind: Sendable, Hashable {
        /// A single data file.
        case file
        /// A directory treated as one dataset — hive-partitioned layouts and
        /// plain directories of files both read as `dir/**/*.<ext>`.
        case dataset
    }

    public let kind: Kind
    public let url: URL
    public let format: FileFormat

    public init(kind: Kind, url: URL, format: FileFormat) {
        self.kind = kind
        self.url = url
        self.format = format
    }

    /// A single file. Its format comes from its own name, since that is the
    /// only thing that decides which reader can open it; an unrecognised
    /// extension reads as parquet, which is what the app did before it read
    /// anything else.
    public static func file(_ url: URL, format: FileFormat? = nil) -> DataSource {
        DataSource(kind: .file, url: url, format: format ?? FileFormat.of(url) ?? .parquet)
    }

    /// A folder read as one table. The format is the caller's to supply — see
    /// `FileTree.format(of:)`, which is what looks in the folder to decide.
    public static func dataset(_ url: URL, format: FileFormat = .parquet) -> DataSource {
        DataSource(kind: .dataset, url: url, format: format)
    }

    /// The folder this source globs, or nil when it is a single file.
    public var datasetRoot: URL? { kind == .dataset ? url : nil }

    public var displayName: String { url.lastPathComponent }

    /// The path handed to the reader. Always passed as a bound parameter,
    /// never interpolated, so paths containing quotes are harmless.
    public var readPath: String {
        switch kind {
        case .file: return url.path
        case .dataset: return url.appendingPathComponent(format.globSuffix).path
        }
    }

    /// The row's physical position within its own file.
    ///
    /// Generated by the reader rather than stored, so it is available on every
    /// file and needs no unique column in the data. That is what makes it the
    /// tiebreaker that turns an `ORDER BY` with ties into a total order — see
    /// `SQLBuilder.rows(source:filters:sort:tiebreak:)`.
    ///
    /// The name is not ours to choose: the option takes a bool, and a file that
    /// already has a column called this cannot be read with it on at all. Hence
    /// `TableModel.canTiebreak`.
    public static let rowNumberColumn = "file_row_number"

    /// The file a row came from.
    ///
    /// `rowNumberColumn` counts within one file, so a source made of several
    /// needs this in front of it to name a row uniquely.
    ///
    /// Deliberately not left as plain `filename`: that is an ordinary thing for
    /// a column to be called, and the option refuses to shadow one. Unlike
    /// `file_row_number` it can be renamed, so a clash is simply avoided.
    public static let fileColumn = "__duckparq_filename"

    /// The virtual columns that together name a row of this source uniquely,
    /// in order of significance.
    ///
    /// Empty for a format whose reader generates neither — vortex, whose
    /// `read_vortex` takes no named options at all. A source with no row
    /// identity gets no tiebreaker, and pages of a broadly-tied sort can
    /// disagree there exactly as they do in SQL mode; see
    /// `SQLBuilder.tiebreakingOrder`, which emits nothing for an empty list.
    public var rowIdentityColumns: [String] {
        guard format.supportsReadOptions else { return [] }
        switch kind {
        case .file: return [Self.rowNumberColumn]
        case .dataset: return [Self.fileColumn, Self.rowNumberColumn]
        }
    }

    /// `read_parquet(...)` / `read_vortex(...)` with the path as parameter
    /// `$index`.
    ///
    /// `filename` and `rowNumber` add the virtual columns above. Both are off
    /// by default because they would otherwise show up as columns of the grid;
    /// the callers that ask for them either alias them (`rowCountsByFile`) or
    /// project them back out (`SQLBuilder.rows`). Both are ignored by a format
    /// whose reader has no such option — asking for one there is a bind error,
    /// and the callers already cope with not getting the column because
    /// `rowIdentityColumns` told them it would not arrive.
    public func readExpression(
        parameterIndex: Int,
        filename: Bool = false,
        rowNumber: Bool = false
    ) -> String {
        let call = format.readFunction
        guard format.supportsReadOptions else { return "\(call)($\(parameterIndex))" }

        let filenameOption = filename ? ", filename = '\(Self.fileColumn)'" : ""
        let rowNumberOption = rowNumber ? ", file_row_number = true" : ""
        switch kind {
        case .file:
            return "\(call)($\(parameterIndex)\(filenameOption)\(rowNumberOption))"
        case .dataset:
            // hive_partitioning surfaces key=value directory names as columns;
            // union_by_name tolerates files whose column order differs.
            return "\(call)($\(parameterIndex), hive_partitioning = true, "
                + "union_by_name = true\(filenameOption)\(rowNumberOption))"
        }
    }
}
