import Foundation

/// What the grid is currently reading.
public enum DataSource: Sendable, Hashable {
    /// A single `.parquet` file.
    case file(URL)
    /// A directory treated as one dataset — hive-partitioned layouts and plain
    /// directories of parquet files both read as `dir/**/*.parquet`.
    case dataset(URL)

    public var url: URL {
        switch self {
        case .file(let url), .dataset(let url): return url
        }
    }

    public var displayName: String { url.lastPathComponent }

    /// The path handed to `read_parquet`. Always passed as a bound parameter,
    /// never interpolated, so paths containing quotes are harmless.
    public var readPath: String {
        switch self {
        case .file(let url): return url.path
        case .dataset(let url): return url.appendingPathComponent("**/*.parquet").path
        }
    }

    /// The row's physical position within its own parquet file.
    ///
    /// Generated by the reader rather than stored, so it is available on every
    /// file and needs no unique column in the data. That is what makes it the
    /// tiebreaker that turns an `ORDER BY` with ties into a total order — see
    /// `SQLBuilder.rows(source:filters:sort:tiebreak:)`.
    ///
    /// The name is not ours to choose: the option takes a bool, and a file that
    /// already has a column called this cannot be read with it on at all. Hence
    /// `TableModel.canTiebreak`.
    public static let rowNumberColumn = "file_row_number"

    /// The file a row came from.
    ///
    /// `rowNumberColumn` counts within one file, so a source made of several
    /// needs this in front of it to name a row uniquely.
    ///
    /// Deliberately not left as plain `filename`: that is an ordinary thing for
    /// a column to be called, and the option refuses to shadow one. Unlike
    /// `file_row_number` it can be renamed, so a clash is simply avoided.
    public static let fileColumn = "__duckparq_filename"

    /// The virtual columns that together name a row of this source uniquely,
    /// in order of significance.
    public var rowIdentityColumns: [String] {
        switch self {
        case .file: return [Self.rowNumberColumn]
        case .dataset: return [Self.fileColumn, Self.rowNumberColumn]
        }
    }

    /// `read_parquet(...)` with the path as parameter `$index`.
    ///
    /// `filename` and `rowNumber` add the virtual columns above. Both are off
    /// by default because they would otherwise show up as columns of the grid;
    /// the callers that ask for them either alias them (`rowCountsByFile`) or
    /// project them back out (`SQLBuilder.rows`).
    public func readExpression(
        parameterIndex: Int,
        filename: Bool = false,
        rowNumber: Bool = false
    ) -> String {
        let filenameOption = filename ? ", filename = '\(Self.fileColumn)'" : ""
        let rowNumberOption = rowNumber ? ", file_row_number = true" : ""
        switch self {
        case .file:
            return "read_parquet($\(parameterIndex)\(filenameOption)\(rowNumberOption))"
        case .dataset:
            // hive_partitioning surfaces key=value directory names as columns;
            // union_by_name tolerates files whose column order differs.
            return "read_parquet($\(parameterIndex), hive_partitioning = true, "
                + "union_by_name = true\(filenameOption)\(rowNumberOption))"
        }
    }
}
